// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PlayerTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PlayerTest', async function() {
    await driver.get("https://elias-espinheira.github.io/MusicPlayer/")
    await driver.manage().window().setRect({ width: 734, height: 700 })
    await driver.findElement(By.css(".fa-sharp")).click()
    await driver.findElement(By.css(".fa-circle-pause")).click()
    await driver.findElement(By.css(".fa-forward")).click()
    await driver.findElement(By.css(".fa-sharp")).click()
    await driver.findElement(By.css(".fa-forward")).click()
    await driver.findElement(By.css(".fa-sharp")).click()
    await driver.findElement(By.css(".fa-circle-pause")).click()
    await driver.findElement(By.css(".fa-forward")).click()
    await driver.findElement(By.css(".fa-sharp")).click()
    await driver.findElement(By.css(".fa-circle-pause")).click()
    await driver.findElement(By.css(".fa-forward")).click()
    await driver.findElement(By.css(".fa-sharp")).click()
    await driver.findElement(By.css(".fa-circle-pause")).click()
    await driver.findElement(By.css(".fa-forward")).click()
    await driver.close()
  })
})
